// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_refresh_tokens.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :execrows
UPDATE refresh_tokens AS token
SET consumed_at = now()
WHERE token.id = $1
  AND token.consumed_at IS NULL
  AND token.revoked_at IS NULL
  AND token.expires_at > now()
  AND EXISTS (
      SELECT 1
      FROM sessions AS session
      WHERE session.id = token.session_id
        AND session.revoked_at IS NULL
        AND session.expires_at > now()
  )
`

// ConsumeRefreshToken chỉ consume token còn hạn/chưa dùng thuộc session chưa revoke/hết hạn; affected rows báo kết quả CAS.
//
//	UPDATE refresh_tokens AS token
//	SET consumed_at = now()
//	WHERE token.id = $1
//	  AND token.consumed_at IS NULL
//	  AND token.revoked_at IS NULL
//	  AND token.expires_at > now()
//	  AND EXISTS (
//	      SELECT 1
//	      FROM sessions AS session
//	      WHERE session.id = token.session_id
//	        AND session.revoked_at IS NULL
//	        AND session.expires_at > now()
//	  )
func (q *Queries) ConsumeRefreshToken(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRefreshToken = `-- name: CreateRefreshToken :execrows
INSERT INTO refresh_tokens (
    id, session_id, token_hash, previous_token_id, created_at, expires_at
)
SELECT $1, session.id, $2, $3,
       $4, $5
FROM sessions AS session
WHERE session.id = $6
  AND session.revoked_at IS NULL
  AND session.expires_at > now()
  AND $5 <= session.expires_at
`

type CreateRefreshTokenParams struct {
	ID              pgtype.UUID
	TokenHash       []byte
	PreviousTokenID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	SessionID       pgtype.UUID
}

// CreateRefreshToken chỉ thêm token khi session còn hiệu lực và token không vượt expiry của session.
//
//	INSERT INTO refresh_tokens (
//	    id, session_id, token_hash, previous_token_id, created_at, expires_at
//	)
//	SELECT $1, session.id, $2, $3,
//	       $4, $5
//	FROM sessions AS session
//	WHERE session.id = $6
//	  AND session.revoked_at IS NULL
//	  AND session.expires_at > now()
//	  AND $5 <= session.expires_at
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.PreviousTokenID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one

SELECT id, session_id, token_hash, previous_token_id, created_at, expires_at, consumed_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
`

// File này khai báo các thao tác sqlc tối thiểu để Auth quản lý digest và trạng thái refresh token.
// GetRefreshTokenByHash tìm token theo SHA-256 digest; caller phải tự kiểm tra session/user lifecycle theo use case.
//
//	SELECT id, session_id, token_hash, previous_token_id, created_at, expires_at, consumed_at, revoked_at
//	FROM refresh_tokens
//	WHERE token_hash = $1
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.PreviousTokenID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSessionRefreshTokens = `-- name: RevokeSessionRefreshTokens :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE session_id = $1
  AND revoked_at IS NULL
`

// RevokeSessionRefreshTokens thu hồi mọi refresh token chưa bị revoke trong session khi logout/revoke session.
//
//	UPDATE refresh_tokens
//	SET revoked_at = now()
//	WHERE session_id = $1
//	  AND revoked_at IS NULL
func (q *Queries) RevokeSessionRefreshTokens(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionRefreshTokens, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
