// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_login.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findLoginCredentialByEmail = `-- name: FindLoginCredentialByEmail :one

SELECT
    user_id::text AS user_id,
    email,
    password_hash
FROM credentials
WHERE email = $1
`

type FindLoginCredentialByEmailRow struct {
	UserID       string
	Email        string
	PasswordHash string
}

// File này chứa các câu lệnh sqlc do Auth sở hữu để lookup Credential và opportunistic rehash trong AUTH-003.
//
//	SELECT
//	    user_id::text AS user_id,
//	    email,
//	    password_hash
//	FROM credentials
//	WHERE email = $1
func (q *Queries) FindLoginCredentialByEmail(ctx context.Context, email string) (FindLoginCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, findLoginCredentialByEmail, email)
	var i FindLoginCredentialByEmailRow
	err := row.Scan(&i.UserID, &i.Email, &i.PasswordHash)
	return i, err
}

const upgradeLoginPasswordHash = `-- name: UpgradeLoginPasswordHash :execrows
UPDATE credentials
SET
    password_hash = $1,
    updated_at = now()
WHERE user_id = $2
  AND password_hash = $3
`

type UpgradeLoginPasswordHashParams struct {
	NewPasswordHash string
	UserID          pgtype.UUID
	OldPasswordHash string
}

// UpgradeLoginPasswordHash
//
//	UPDATE credentials
//	SET
//	    password_hash = $1,
//	    updated_at = now()
//	WHERE user_id = $2
//	  AND password_hash = $3
func (q *Queries) UpgradeLoginPasswordHash(ctx context.Context, arg UpgradeLoginPasswordHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, upgradeLoginPasswordHash, arg.NewPasswordHash, arg.UserID, arg.OldPasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
