// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_registration.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationCredential = `-- name: CreateRegistrationCredential :exec

INSERT INTO credentials (
    user_id,
    email,
    password_hash
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateRegistrationCredentialParams struct {
	UserID       pgtype.UUID
	Email        string
	PasswordHash string
}

// File này chứa câu lệnh sqlc do Auth sở hữu để ghi Credential trong registration transaction của AUTH-001.
//
//	INSERT INTO credentials (
//	    user_id,
//	    email,
//	    password_hash
//	) VALUES (
//	    $1,
//	    $2,
//	    $3
//	)
func (q *Queries) CreateRegistrationCredential(ctx context.Context, arg CreateRegistrationCredentialParams) error {
	_, err := q.db.Exec(ctx, createRegistrationCredential, arg.UserID, arg.Email, arg.PasswordHash)
	return err
}
