// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: database.sql

package dbsqlc

import (
	"context"
)

const databasePing = `-- name: DatabasePing :one

SELECT 1::bigint AS value
`

// File này chứa query kỹ thuật tối thiểu để DB-005 kiểm chứng sqlc codegen, pgx/v5, context và transaction wiring.
//
//	SELECT 1::bigint AS value
func (q *Queries) DatabasePing(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, databasePing)
	var value int64
	err := row.Scan(&value)
	return value, err
}
