// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID            pgtype.UUID
	Name          string
	Slug          string
	Description   pgtype.Text
	LogoObjectKey pgtype.Text
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Cart struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CheckedOutAt pgtype.Timestamptz
	AbandonedAt  pgtype.Timestamptz
}

type CartItem struct {
	ID        pgtype.UUID
	CartID    pgtype.UUID
	ShopID    pgtype.UUID
	SkuID     pgtype.UUID
	Quantity  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Category struct {
	ID             pgtype.UUID
	ParentID       pgtype.UUID
	Name           string
	Slug           string
	IconObjectKey  pgtype.Text
	ImageObjectKey pgtype.Text
	Status         string
	SortOrder      int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Credential struct {
	UserID            pgtype.UUID
	Email             string
	PasswordHash      string
	EmailVerifiedAt   pgtype.Timestamptz
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type InventoryReservation struct {
	ID             pgtype.UUID
	ReferenceType  string
	ReferenceID    pgtype.UUID
	IdempotencyKey string
	RequestHash    string
	Status         string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CommittedAt    pgtype.Timestamptz
	ReleasedAt     pgtype.Timestamptz
	ExpiredAt      pgtype.Timestamptz
}

type InventoryReservationItem struct {
	ID               pgtype.UUID
	ReservationID    pgtype.UUID
	InventoryStockID pgtype.UUID
	Quantity         int64
	CreatedAt        pgtype.Timestamptz
}

type InventoryStock struct {
	ID               pgtype.UUID
	ShopID           pgtype.UUID
	WarehouseID      pgtype.UUID
	SkuID            pgtype.UUID
	OnHandQuantity   int64
	ReservedQuantity int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Order struct {
	ID                    pgtype.UUID
	OrderNumber           string
	OrderType             string
	ParentOrderID         pgtype.UUID
	ParentOrderType       pgtype.Text
	CheckoutReferenceID   pgtype.UUID
	UserID                pgtype.UUID
	ShopID                pgtype.UUID
	Status                string
	Currency              string
	SubtotalAmount        int64
	DiscountAmount        int64
	TaxAmount             int64
	ShippingAmount        int64
	TotalAmount           int64
	CustomerNameSnapshot  string
	CustomerEmailSnapshot pgtype.Text
	CustomerPhoneSnapshot pgtype.Text
	ShippingRecipientName pgtype.Text
	ShippingPhone         pgtype.Text
	ShippingAddressLine1  pgtype.Text
	ShippingAddressLine2  pgtype.Text
	ShippingWard          pgtype.Text
	ShippingDistrict      pgtype.Text
	ShippingCity          pgtype.Text
	ShippingCountryCode   pgtype.Text
	ShopNameSnapshot      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ConfirmedAt           pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
	CancelledAt           pgtype.Timestamptz
}

type OrderItem struct {
	ID                  pgtype.UUID
	OrderID             pgtype.UUID
	ShopID              pgtype.UUID
	ProductID           pgtype.UUID
	VariantID           pgtype.UUID
	SkuID               pgtype.UUID
	SkuCodeSnapshot     string
	ProductNameSnapshot string
	VariantNameSnapshot pgtype.Text
	SkuNameSnapshot     pgtype.Text
	AttributesSnapshot  []byte
	Quantity            int64
	UnitPriceAmount     int64
	DiscountAmount      int64
	TaxAmount           int64
	LineSubtotalAmount  int64
	LineTotalAmount     int64
	CreatedAt           pgtype.Timestamptz
}

type OrderStatusHistory struct {
	ID         pgtype.UUID
	OrderID    pgtype.UUID
	FromStatus pgtype.Text
	ToStatus   string
	ActorType  string
	ActorID    pgtype.UUID
	ReasonCode pgtype.Text
	Reason     pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type PaymentRefund struct {
	ID                   pgtype.UUID
	PaymentTransactionID pgtype.UUID
	Provider             string
	ProviderRefundID     pgtype.Text
	IdempotencyKey       string
	RequestHash          string
	Amount               int64
	CurrencyCode         string
	Status               string
	Reason               pgtype.Text
	FailureCode          pgtype.Text
	FailureMessage       pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ProcessingAt         pgtype.Timestamptz
	SucceededAt          pgtype.Timestamptz
	FailedAt             pgtype.Timestamptz
	CancelledAt          pgtype.Timestamptz
}

type PaymentTransaction struct {
	ID                    pgtype.UUID
	ParentOrderID         pgtype.UUID
	ParentOrderType       string
	Provider              string
	ProviderPaymentID     pgtype.Text
	IdempotencyKey        string
	RequestHash           string
	Amount                int64
	CurrencyCode          string
	AllocatedRefundAmount int64
	Status                string
	FailureCode           pgtype.Text
	FailureMessage        pgtype.Text
	ExpiresAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ProcessingAt          pgtype.Timestamptz
	SucceededAt           pgtype.Timestamptz
	FailedAt              pgtype.Timestamptz
	CancelledAt           pgtype.Timestamptz
}

type PaymentWebhookEvent struct {
	ID                   pgtype.UUID
	Provider             string
	ProviderEventID      string
	ProviderPaymentID    pgtype.Text
	PaymentTransactionID pgtype.UUID
	EventType            string
	PayloadHash          string
	ProcessingStatus     string
	ReceivedAt           pgtype.Timestamptz
	ProcessedAt          pgtype.Timestamptz
	LastError            pgtype.Text
}

type Product struct {
	ID                 pgtype.UUID
	ShopID             pgtype.UUID
	CategoryID         pgtype.UUID
	BrandID            pgtype.UUID
	Name               string
	Slug               string
	Description        pgtype.Text
	MainImageObjectKey pgtype.Text
	WeightG            pgtype.Int4
	PackageLengthMm    pgtype.Int4
	PackageWidthMm     pgtype.Int4
	PackageHeightMm    pgtype.Int4
	Status             string
	RejectionReason    pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	PublishedAt        pgtype.Timestamptz
	ArchivedAt         pgtype.Timestamptz
}

type ProductVariant struct {
	ID             pgtype.UUID
	ProductID      pgtype.UUID
	ShopID         pgtype.UUID
	Name           string
	Attributes     []byte
	ImageObjectKey pgtype.Text
	Status         string
	Position       int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ArchivedAt     pgtype.Timestamptz
}

type SellerAccount struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	SuspendedAt pgtype.Timestamptz
	ClosedAt    pgtype.Timestamptz
}

type Session struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	IpAddress      *netip.Addr
	UserAgent      pgtype.Text
	CreatedAt      pgtype.Timestamptz
	LastActivityAt pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type Shop struct {
	ID              pgtype.UUID
	Name            string
	Slug            string
	Description     pgtype.Text
	LogoObjectKey   pgtype.Text
	BannerObjectKey pgtype.Text
	Phone           pgtype.Text
	Email           pgtype.Text
	IsOfficial      bool
	CurrencyCode    string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ClosedAt        pgtype.Timestamptz
}

type ShopMembership struct {
	ID                       pgtype.UUID
	ShopID                   pgtype.UUID
	SellerAccountID          pgtype.UUID
	CreatedBySellerAccountID pgtype.UUID
	Role                     string
	Status                   string
	InvitedAt                pgtype.Timestamptz
	AcceptedAt               pgtype.Timestamptz
	RevokedAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type Sku struct {
	ID                        pgtype.UUID
	VariantID                 pgtype.UUID
	ShopID                    pgtype.UUID
	SkuCode                   string
	Barcode                   pgtype.Text
	Name                      string
	Attributes                []byte
	ImageObjectKey            pgtype.Text
	PriceAmountMinor          int64
	CompareAtPriceAmountMinor pgtype.Int8
	CurrencyCode              string
	WeightG                   pgtype.Int4
	PackageLengthMm           pgtype.Int4
	PackageWidthMm            pgtype.Int4
	PackageHeightMm           pgtype.Int4
	Status                    string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	ArchivedAt                pgtype.Timestamptz
}

type StockMovement struct {
	ID               pgtype.UUID
	InventoryStockID pgtype.UUID
	MovementType     string
	QuantityDelta    int64
	ReferenceType    pgtype.Text
	ReferenceID      pgtype.UUID
	Reason           pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type UserAddress struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Label          pgtype.Text
	RecipientName  string
	RecipientPhone string
	AddressLine1   string
	AddressLine2   pgtype.Text
	Ward           pgtype.Text
	District       pgtype.Text
	Province       string
	PostalCode     pgtype.Text
	CountryCode    string
	IsDefault      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Voucher struct {
	ID                  pgtype.UUID
	Code                string
	Scope               string
	ShopID              pgtype.UUID
	DiscountType        string
	DiscountValue       int64
	MaxDiscountAmount   pgtype.Int8
	MinimumOrderAmount  int64
	CurrencyCode        string
	UsageLimit          pgtype.Int8
	UsageLimitPerUser   pgtype.Int8
	AllocatedUsageCount int64
	StartsAt            pgtype.Timestamptz
	EndsAt              pgtype.Timestamptz
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type VoucherUsage struct {
	ID                  pgtype.UUID
	VoucherID           pgtype.UUID
	UserID              pgtype.UUID
	CheckoutReferenceID pgtype.UUID
	OrderID             pgtype.UUID
	ParentOrderType     pgtype.Text
	DiscountAmount      int64
	CurrencyCode        string
	Status              string
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	CommittedAt         pgtype.Timestamptz
	ReleasedAt          pgtype.Timestamptz
	ExpiredAt           pgtype.Timestamptz
}

type Warehouse struct {
	ID         pgtype.UUID
	ShopID     pgtype.UUID
	Name       string
	Code       string
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ArchivedAt pgtype.Timestamptz
}
