// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_login.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findLoginUserStatus = `-- name: FindLoginUserStatus :one

SELECT status
FROM users
WHERE id = $1
`

// File này chứa câu lệnh sqlc do User module sở hữu để Auth kiểm tra account lifecycle sau khi password đúng.
//
//	SELECT status
//	FROM users
//	WHERE id = $1
func (q *Queries) FindLoginUserStatus(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, findLoginUserStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}
