// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_registration.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationUser = `-- name: CreateRegistrationUser :exec

INSERT INTO users (
    id,
    display_name
) VALUES (
    $1,
    $2
)
`

type CreateRegistrationUserParams struct {
	ID          pgtype.UUID
	DisplayName string
}

// File này chứa câu lệnh sqlc do User module sở hữu để tạo profile tối thiểu trong registration transaction của AUTH-001.
//
//	INSERT INTO users (
//	    id,
//	    display_name
//	) VALUES (
//	    $1,
//	    $2
//	)
func (q *Queries) CreateRegistrationUser(ctx context.Context, arg CreateRegistrationUserParams) error {
	_, err := q.db.Exec(ctx, createRegistrationUser, arg.ID, arg.DisplayName)
	return err
}
